### ISSUE TITLE
cacophony-0.11.0 fails to build with crypton-1.1 and ram

### ISSUE THREAD

**Issue by juhp** [haskell-cryptography/cacophony#19]
```
       Building library for cacophony-0.11.0...
       [ 1 of 23] Compiling Crypto.Noise.Cipher
       [ 2 of 23] Compiling Crypto.Noise.Cipher.AESGCM
       /home/curators/work/unpack-dir/unpacked/cacophony-0.11.0-5571e9cd94b556eef2eafd6fb882c47d8b115c2c355ea4ff7d6a03f61e300861/src/Crypto/Noise/Cipher/AESGCM.hs:54:11: error: [GHC-39999]
           • No instance for ‘ram-0.22.0:Data.ByteArray.Types.ByteArray
                                ScrubbedBytes’
               arising from a use of ‘aeadSimpleEncrypt’
           • In the second argument of ‘($)’, namely
               ‘aeadSimpleEncrypt aead ad plaintext 16’
             In the expression: CTAES $ aeadSimpleEncrypt aead ad plaintext 16
             In an equation for ‘encrypt’:
                 encrypt (SKAES k) (NAES n) ad plaintext
                   = CTAES $ aeadSimpleEncrypt aead ad plaintext 16
                   where
                       state = throwCryptoError . cipherInit $ k :: AES256
                       aead = throwCryptoError $ aeadInit AEAD_GCM state n
          |
       54 |   CTAES $ aeadSimpleEncrypt aead ad plaintext 16
          |           ^^^^^^^^^^^^^^^^^

       /home/curators/work/unpack-dir/unpacked/cacophony-0.11.0-5571e9cd94b556eef2eafd6fb882c47d8b115c2c355ea4ff7d6a03f61e300861/src/Crypto/Noise/Cipher/AESGCM.hs:57:32: error: [GHC-39999]
           • No instance for ‘ram-0.22.0:Data.ByteArray.Types.ByteArrayAccess
                                Bytes’
               arising from a use of ‘aeadInit’
             There are instances for similar types:
               instance ram-0.22.0:Data.ByteArray.Types.ByteArrayAccess
                          ram-0.22.0:Data.ByteArray.Bytes.Bytes
                 -- Defined in ‘ram-0.22.0:Data.ByteArray.Bytes’
           • In the second argument of ‘($)’, namely
               ‘aeadInit AEAD_GCM state n’
             In the expression: throwCryptoError $ aeadInit AEAD_GCM state n
             In an equation for ‘aead’:
                 aead = throwCryptoError $ aeadInit AEAD_GCM state n
          |
       57 |     aead  = throwCryptoError $ aeadInit AEAD_GCM state n
          |                                ^^^^^^^^

       /home/curators/work/unpack-dir/unpacked/cacophony-0.11.0-5571e9cd94b556eef2eafd6fb882c47d8b115c2c355ea4ff7d6a03f61e300861/src/Crypto/Noise/Cipher/AESGCM.hs:100:42: error: [GHC-39999]
           • No instance for ‘memory-0.18.0:Data.ByteArray.Types.ByteArrayAccess
                                AuthTag’
               arising from a use of ‘convert’
           • In the second argument of ‘mappend’, namely ‘convert a’
             In the expression: ct `mappend` convert a
             In an equation for ‘ctToBytes’:
                 ctToBytes (CTAES (a, ct)) = ct `mappend` convert a
           |
       100 | ctToBytes (CTAES (a, ct)) = ct `mappend` convert a
           |                                          ^^^^^^^

       /home/curators/work/unpack-dir/unpacked/cacophony-0.11.0-5571e9cd94b556eef2eafd6fb882c47d8b115c2c355ea4ff7d6a03f61e300861/src/Crypto/Noise/Cipher/AESGCM.hs:105:21: error: [GHC-39999]
           • No instance for ‘ByteArray ram-0.22.0:Data.ByteArray.Bytes.Bytes’
               arising from a use of ‘convert’
             There are instances for similar types:
               instance ByteArray Bytes
                 -- Defined in ‘memory-0.18.0:Data.ByteArray.Bytes’
           • In the second argument of ‘(.)’, namely ‘convert’
             In the first argument of ‘($)’, namely ‘AuthTag . convert’
             In the expression:
               AuthTag . convert $ drop (length bytes - 16) bytes
           |
       105 |   CTAES ( AuthTag . convert $ drop (length bytes - 16) bytes
           |                     ^^^^^^^

       [ 3 of 23] Compiling Crypto.Noise.Cipher.ChaChaPoly1305
       /home/curators/work/unpack-dir/unpacked/cacophony-0.11.0-5571e9cd94b556eef2eafd6fb882c47d8b115c2c355ea4ff7d6a03f61e300861/src/Crypto/Noise/Cipher/ChaChaPoly1305.hs:50:27: error: [GHC-39999]
           • No instance for ‘memory-0.18.0:Data.ByteArray.Types.ByteArrayAccess
                                P.Auth’
               arising from a use of ‘convert’
           • In the first argument of ‘P.Auth’, namely ‘(convert authTag)’
             In the expression: P.Auth (convert authTag)
             In the first argument of ‘CTCCP1305’, namely
               ‘(out, P.Auth (convert authTag))’
          |
       50 |   CTCCP1305 (out, P.Auth (convert authTag))
          |                           ^^^^^^^

       /home/curators/work/unpack-dir/unpacked/cacophony-0.11.0-5571e9cd94b556eef2eafd6fb882c47d8b115c2c355ea4ff7d6a03f61e300861/src/Crypto/Noise/Cipher/ChaChaPoly1305.hs:52:42: error: [GHC-39999]
           • No instance for ‘ram-0.22.0:Data.ByteArray.Types.ByteArrayAccess
                                ScrubbedBytes’
               arising from a use of ‘CCP.initialize’
           • In the second argument of ‘($)’, namely ‘CCP.initialize k n’
             In the expression: throwCryptoError $ CCP.initialize k n
             In an equation for ‘initState’:
                 initState = throwCryptoError $ CCP.initialize k n
          |
       52 |     initState       = throwCryptoError $ CCP.initialize k n
          |                                          ^^^^^^^^^^^^^^
```
